// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmk63lECQ0q4V9eazXauczaj_gKfrjTZY',
    appId: '1:826448631640:web:07efa7c1659182ba05f72d',
    messagingSenderId: '826448631640',
    projectId: 'actapp-8b644',
    authDomain: 'actapp-8b644.firebaseapp.com',
    storageBucket: 'actapp-8b644.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkoTBznkXwmRQYDQh8rV2UfjTwHqDRjI',
    appId: '1:826448631640:android:15edea85d5afbc9805f72d',
    messagingSenderId: '826448631640',
    projectId: 'actapp-8b644',
    storageBucket: 'actapp-8b644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0jBJWnnVtsIb9-yBL3qdc1sCoJd9zho',
    appId: '1:826448631640:ios:26ac8f676dd2db7f05f72d',
    messagingSenderId: '826448631640',
    projectId: 'actapp-8b644',
    storageBucket: 'actapp-8b644.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0jBJWnnVtsIb9-yBL3qdc1sCoJd9zho',
    appId: '1:826448631640:ios:26ac8f676dd2db7f05f72d',
    messagingSenderId: '826448631640',
    projectId: 'actapp-8b644',
    storageBucket: 'actapp-8b644.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmk63lECQ0q4V9eazXauczaj_gKfrjTZY',
    appId: '1:826448631640:web:6b73956bc0ebc8de05f72d',
    messagingSenderId: '826448631640',
    projectId: 'actapp-8b644',
    authDomain: 'actapp-8b644.firebaseapp.com',
    storageBucket: 'actapp-8b644.firebasestorage.app',
  );
}
